In [1]:
! pip install pandas

Collecting pandas
  Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl (12.8 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed numpy-2.3.2 pandas-2.3.2 pytz-2025.2 tzdata-2025.2

In [2]:
! pip install numpy

Requirement already satisfied: numpy in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (2.3.2)

In [4]:
! pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Using cached matplotlib-3.10.6-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached fonttools-4.59.2-cp313-cp313-win_amd64.whl.metadata (111 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pillow-11.3.0-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pc\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.6-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.59.2-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Using cached pillow-11.3.0-cp313-cp313-win_amd64.whl (7.0 MB)
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/8 [pyparsing]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.59.2 kiwisolver-1.4.9 matplotlib-3.10.6 pillow-11.3.0 pyparsing-3.2.3 seaborn-0.13.2

In [5]:
! pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\pc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pc\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
data=pd.read_csv('Suicide_data.csv')
df=pd.DataFrame(data)
df

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [5]:
#### Descriptive analysis
df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             27820 non-null  object
 1   year                27820 non-null  int64
 2   sex                 27820 non-null  object
 3   age                 27820 non-null  object
 4   suicides_no         27820 non-null  int64
 5   population          27820 non-null  int64
 6   suicides/100k pop   27820 non-null  float64
 7   country-year        27820 non-null  object
 8   HDI for year        8364 non-null   float64
 9    gdp_for_year ($)   27820 non-null  object
 10  gdp_per_capita ($)  27820 non-null  int64
 11  generation          27820 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB

In [7]:
df.describe()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
count,27820.000000,27820.000000,2.782000e+04,27820.000000,8364.000000,27820.000000
mean,2001.258375,242.574407,1.844794e+06,12.816097,0.776601,16866.464414
std,8.469055,902.047917,3.911779e+06,18.961511,0.093367,18887.576472
min,1985.000000,0.000000,2.780000e+02,0.000000,0.483000,251.000000
25%,1995.000000,3.000000,9.749850e+04,0.920000,0.713000,3447.000000
50%,2002.000000,25.000000,4.301500e+05,5.990000,0.779000,9372.000000
75%,2008.000000,131.000000,1.486143e+06,16.620000,0.855000,24874.000000
max,2016.000000,22338.000000,4.380521e+07,224.970000,0.944000,126352.000000

In [8]:
#drop column population
df=df.drop('population',axis=1)
df

,country,year,sex,age,suicides_no,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [9]:
#rename column sex to gender
df.rename(columns={'sex': 'gender'},inplace=True)
df

,country,year,gender,age,suicides_no,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers